# .docker-compose.yml

version: '3'

services:
  db:
    image: mysql:5.7
    environment:
       MYSQL_ROOT_PASSWORD: lalala
       MYSQL_DATABASE: jumanji_db
       MYSQL_USER: sotiris
       MYSQL_PASSWORD: skavvouras
    ports:
      - "9906:3306"
  web:
    build: './php/'
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    ports:
      - "8080:80"
    tty: true
